//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CassiniDev.FixtureExamples.NUnit.TestWCFServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HelloWorldArgs", Namespace="http://schemas.datacontract.org/2004/07/CassiniDev.FixtureExamples.TestWeb")]
    [System.SerializableAttribute()]
    public partial class HelloWorldArgs : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://TestWebApp", ConfigurationName="TestWCFServiceReference.ITestWCFService")]
    public interface ITestWCFService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://TestWebApp/ITestWCFService/HelloWorld", ReplyAction="http://TestWebApp/ITestWCFService/HelloWorldResponse")]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://TestWebApp/ITestWCFService/HelloWorldWithArgsInOut", ReplyAction="http://TestWebApp/ITestWCFService/HelloWorldWithArgsInOutResponse")]
        CassiniDev.FixtureExamples.NUnit.TestWCFServiceReference.HelloWorldArgs HelloWorldWithArgsInOut(CassiniDev.FixtureExamples.NUnit.TestWCFServiceReference.HelloWorldArgs args);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface ITestWCFServiceChannel : CassiniDev.FixtureExamples.NUnit.TestWCFServiceReference.ITestWCFService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class TestWCFServiceClient : System.ServiceModel.ClientBase<CassiniDev.FixtureExamples.NUnit.TestWCFServiceReference.ITestWCFService>, CassiniDev.FixtureExamples.NUnit.TestWCFServiceReference.ITestWCFService {
        
        public TestWCFServiceClient() {
        }
        
        public TestWCFServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TestWCFServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TestWCFServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TestWCFServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public CassiniDev.FixtureExamples.NUnit.TestWCFServiceReference.HelloWorldArgs HelloWorldWithArgsInOut(CassiniDev.FixtureExamples.NUnit.TestWCFServiceReference.HelloWorldArgs args) {
            return base.Channel.HelloWorldWithArgsInOut(args);
        }
    }
}
